apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-10-16T12:52:51Z"
  labels:
    app: flaskapp
  name: flaskapp
  namespace: default
  resourceVersion: "3942"
  uid: 70650ba0-3385-4e22-98ee-162ebf51eb3e
spec:
  clusterIP: 10.106.22.209
  clusterIPs:
  - 10.106.22.209
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30841
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
