apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp
  name: flaskapp
  namespace: myapp
spec:
  ports:
  - nodePort: 30841
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapp
  type: NodePort
